//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazHda.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servicios.electricaribe.com/irregularidades_services/IrregularidadesServi" +
            "ce")]
        public string url_ws {
            get {
                return ((string)(this["url_ws"]));
            }
            set {
                this["url_ws"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sintegrales")]
        public string user_ws {
            get {
                return ((string)(this["user_ws"]));
            }
            set {
                this["user_ws"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sintegrales1808")]
        public string pass_ws {
            get {
                return ((string)(this["pass_ws"]));
            }
            set {
                this["pass_ws"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hgiservice.herramientasgnf.com:8080/rest/")]
        public string url_hda {
            get {
                return ((string)(this["url_hda"]));
            }
            set {
                this["url_hda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hgi")]
        public string user_hda {
            get {
                return ((string)(this["user_hda"]));
            }
            set {
                this["user_hda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hgi")]
        public string pass_hda {
            get {
                return ((string)(this["pass_hda"]));
            }
            set {
                this["pass_hda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hda.herramientasgnf.com:8080/rest/serviceorder/")]
        public string url_hda_docu {
            get {
                return ((string)(this["url_hda_docu"]));
            }
            set {
                this["url_hda_docu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hgiservice.herramientasgnf.com:8080/api/media/")]
        public string url_hda_fotos {
            get {
                return ((string)(this["url_hda_fotos"]));
            }
            set {
                this["url_hda_fotos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hgiservice.herramientasgnf.com:8080/api/signatures/")]
        public string url_hda_firma {
            get {
                return ((string)(this["url_hda_firma"]));
            }
            set {
                this["url_hda_firma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\HGI2\\File\\Documentos")]
        public string dir_imagenes {
            get {
                return ((string)(this["dir_imagenes"]));
            }
            set {
                this["dir_imagenes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("integrated security=SSPI;data source=WIN-9L0BNLD7OU9\\\\SQLEXPRESS;persist security" +
            " info=False;initial catalog=BDHGI2")]
        public string conexion {
            get {
                return ((string)(this["conexion"]));
            }
            set {
                this["conexion"] = value;
            }
        }
    }
}
